name: CelebA-MSDINet2e
model_type: ImageRestorationModel2
num_gpu: 1 # set num_gpu: 0 for cpu mode
manual_seed: 10

# dataset and data loader settings
datasets:

  test:
    name: CelebA-val
    type: PairedImageDataset
    # dataroot_gt: /eva_data1/shlu2240/Dataset/celeba_hq_02_4/test/hq
    # dataroot_lq: /eva_data1/shlu2240/Dataset/celeba_hq_02_4/test/lq/4

    dataroot_gt: /eva_data1/shlu2240/DDNM/exp/image_samples/test_IR/x0_t
    dataroot_lq: /eva_data1/shlu2240/DDNM/exp/image_samples/test_IR/x0_t
    
    gt_size: 256
    io_backend:
      type: disk

# network structures
network_g:
  type: MSDI2E
  # wf: 64
  hin_position_left: 0
  hin_position_right: 4

path:
  root: /eva_data1/shlu2240/Learning_Degradation
  pretrain_network_g: /eva_data3/shlu2240/checkpoints/LD/celeba_x8.pth #v1
  # pretrain_network_g: /eva_data3/shlu2240/checkpoints/LD/celeba_x4_x0_t.pth #v2
  # pretrain_network_g: /eva_data3/shlu2240/checkpoints/LD/celeba_x4_x0_t_SameTarget.pth
  # pretrain_network_g: /eva_data3/shlu2240/checkpoints/LD/celeba_x4_x0t_timestep.pth
  resume_state: ~

# validation settings
val:
  save_img: true
  grids: false
  crop_size: 256

  metrics:
    psnr: 
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false
